### ISSUE TITLE
Ability to change the formatting Ingame <-> Discord

### ISSUE THREAD

**Issue by Bulluk** [GeheimagentNr1/DiscordIntegration#11]
**Is your feature request related to a problem? Please describe.**
Unable to change the formatting.

**Describe the solution you'd like**
In the config file able to change the formatting for all messages sent from ingame to discord, and how discord messages are received ingame. For example, formatted/embedded messages in discord are shown literally ingame. I will provide screenshots for better understanding if desired.

**Describe alternatives you've considered**
None exist, as far as I know.

**Comment by GeheimagentNr1** [comment]
Yes, it would be nice, if you provide screenshots, because I don't exactly understand, what features you want.
