### ISSUE TITLE
Can we get 1.18.2 support?

### ISSUE THREAD

**Issue by entheosbardou** [GeheimagentNr1/DiscordIntegration#14]
Can we get 1.18.2 support?

**Comment by GeheimagentNr1** [comment]
I currently don't have Internet, but a soon as I have Internet again, I will build a 1.18.2 version of all of my mods.

**Comment by GeheimagentNr1** [comment]
My mods are now all available for 1.18.2.
Have fun playing modded Minecraft with my mods.
