### ISSUE TITLE
Emojiful Support

### ISSUE THREAD

**Issue by WizardLumine** [GeheimagentNr1/DiscordIntegration#17]
**_Is your feature request related to a problem? Please describe._**
I'm trying to use this with the Emojiful mod. You can send an emoji in game chat, and it will show up in Discord. However, if you send an emoji in Discord, it will just show up as a box in the game chat.

**_Describe the solution you'd like_**
Possibly have some sort of emoji detection, and a config option to send the shortcode to the chat instead of trying to send an emoji

**_Additional context_**
![Discord_mPc7edqV92](https://user-images.githubusercontent.com/61512530/174408378-28e9ad42-8ef9-46ba-b8a0-77767460b9de.png)
![javaw_PCPIDAvk4T](https://user-images.githubusercontent.com/61512530/174408400-899f2642-c592-4173-adc9-bcba96d713b8.png)

**Comment by GeheimagentNr1** [comment]
Because Emojiful does not provide an API to convert Unicode-Emojis back into emoji names, that can be used to make Emojiful display its emojis, this feature request has to be refused.
