### ISSUE TITLE
Discord Linking/Commands with parameters

### ISSUE THREAD

**Issue by Proton-PLU5** [GeheimagentNr1/DiscordIntegration#2]
**Is your feature request related to a problem? Please describe.**
I am looking for a linking method. So that when a player tries to join they have to link their accounts in order to join.

**Describe the solution you'd like**
Somewhat of a Linking mechanism that adds and removes whitelisted players. Easy solution for whitelists

**Describe alternatives you've considered**
Tried making a custom command, It didn't work.

**Additional context**
None

**Comment by GeheimagentNr1** [comment]
If I understand you right, you want a mechanism, that a player can tell the Minecraft server "This is my Minecraft name" and the server whitelists the player automatically. Am I correct?

But how shall be verified, that the player is the owner of the Minecraft account, he/she supplies? Discord does not have a mechanism to connect Minecraft and Discord account.

If I am correct, and you want a mechanism, that the players can whitelist them self, then you could also just deactivate the whitelist, and it would have the same effect.

**Comment by Proton-PLU5** [comment]
I have some knowledge in discord bot making, But it is not JDA rather python, What you could do is make the user run a command on discord like **!link username here**. 

The bot will then whitelist that user on the server using their name and UUID (No idea how to get the UUID may be checking when a player joins). 

Then give them a role that the server owner puts in the config. And maybe even add some extra options for linked players. Also once a person is linked they should not be able to link another account. I write this because I see great potential in this mod. 

If you do get it working, That will be fantastic and might increase the total downloads or popularity of the mod.

**Comment by Proton-PLU5** [comment]
Also, I have one more suggestion, I like the custom commands but it will have far more functionality if you implemented the use of arguments or for example **!say whatever you want to say**. This might be a daunting task but if you pull this off, The mod will get far more interest as all of the other 1.16.5 discord Minecraft mods do not have any or good support to this, The ones that do have it mostly doesn't work at all.

If you have discord you can contact me Proton+#1867 ^-^

**Comment by GeheimagentNr1** [comment]
I have thought about feature request over the last weeks and came to the question, if you need a feature to link Discord and Minecraft users or if a custom command with parameter would be enough?  
For example, the user "ExampleDiscordUser" has a Minecraft account with the name "ExampleMinecraft" and if the uses the Discord command "!whitelist add ExampleMinecraft" the "/whitelist add ExampleMinecraft" is executed in Minecraft and the user is whitelisted.

**Comment by GeheimagentNr1** [comment]
<table><tbody><tr><th>Status:</th><td>Implemented</td></tr><tr><th>Issue type:</th><td>New Feature</td></tr><tr><th>Fix type:</th><td>New feature</td></tr><tr><th>Fix version:</th><td>2.2.0</td></tr><tr><th>Fix release date:</th><td>05.08.2021</td></tr></tbody></table>

**TODOs:**

*    [x]  Add a flag to the commands' config options. If it's active, everything attached to the Discord command will be attachted to the Minecraft command, so Parameters can be transferred from Discord to Minecraft commands.
