### ISSUE TITLE
Highly customizable message options

### ISSUE THREAD

**Issue by AbzZero** [GeheimagentNr1/DiscordIntegration#24]
**Is your feature request related to a problem? Please describe.**
Discord messages sent in minecraft and vice versa have a unchangable format provided by the mod.
Ex.
'[Username] Message' - Minecraft and Discord
'**username** <config message> <advancement>' - join, leave, advancements in Discord

**Describe the solution you'd like**
The ability to change finer details of the formats of the message, with placeholders like %player%, %message%, %advancement%.
Bold text, italics, underlined text, text color, etc. should be configurable by the player.
Some placeholders should be optional.
Ex.
Discord -> Minecraft format: '<%nickname% (%username%)> %message%'
With the discord name 'Robert', nickname 'Bob', and sent message 'Hello!', it would send in minecraft: '<Bob (Robert)> Hello!'

**Describe alternatives you've considered**
A set of configs to change the border text (for things like []), text formatting, etc.

**Additional context**
Text color is probably not possible on discord side?

┆Issue is synchronized with this [Trello card](https://trello.com/c/kilImnoO) by [Unito](https://www.unito.io)

**Comment by GeheimagentNr1** [comment]
<table><tbody><tr><th>Status:</th><td>Released</td></tr><tr><th>Issue type:</th><td>New Feature</td></tr><tr><th>Fix type:</th><td>New feature</td></tr><tr><th>Fix version:</th><td>3.0.0</td></tr><tr><th>Fix release date:</th><td>12.11.2023</td></tr></tbody></table>

**TODOs:**

*   [x] Make all messages customizable.

**Comment by GeheimagentNr1** [comment]
All messages shown in Discord and shown in the Minecraft chat are now customizable. For the Discord to Minecraft messages, the JSON format can be optionally used: https://minecraft.fandom.com/wiki/Commands/tellraw#Examples

Implemented with version 3.0.0 for Minecraft 1.18.1, 1.18.2, 1.19.2, 1.19.4 and 1.20.2
CurseForge: https://www.curseforge.com/minecraft/mc-mods/discord-integration
Modrith: https://modrinth.com/mod/discord-integration-(di)
