### ISSUE TITLE
Block 'server' messages passing through to Discord

### ISSUE THREAD

**Issue by trentnbauer** [GeheimagentNr1/DiscordIntegration#25]
**Is your feature request related to a problem? Please describe.**
I have a nightly reboot & backup CRON that involves sending messages using '/say' and these are passed onto Discord. As my servers are relatively low population, or go through often quiet periods this looks pretty poor in the Discord channel over and over
![image](https://github.com/GeheimagentNr1/DiscordIntegration/assets/45578026/3c217518-354a-4d18-8bfb-5fe34be5ca6c)

**Describe the solution you'd like**
The ability to stop server messages from being passed through to Discord

**Describe alternatives you've considered**
I'm currently looking into mods to handle this

**Additional context**

┆Issue is synchronized with this [Trello card](https://trello.com/c/aitikmVT) by [Unito](https://www.unito.io)

**Comment by GeheimagentNr1** [comment]
<table><tbody><tr><th>Status:</th><td>Released</td></tr><tr><th>Issue type:</th><td>New Feature</td></tr><tr><th>Fix type:</th><td>New feature</td></tr><tr><th>Fix version:</th><td>3.0.0</td></tr><tr><th>Fix release date:</th><td>12.11.2023</td></tr></tbody></table>

**TODOs:**

*   [x] Add Feature/Config flag to disable the transmissions from server chat messages to the Discord chat

**Comment by GeheimagentNr1** [comment]
Implemented with version 3.0.0 for Minecraft 1.18.1, 1.18.2, 1.19.2, 1.19.4 and 1.20.2
CurseForge: https://www.curseforge.com/minecraft/mc-mods/discord-integration
Modrith: https://modrinth.com/mod/discord-integration-(di)
