### ISSUE TITLE
Messages from discord to minecraft are not showing up

### ISSUE THREAD

**Issue by Subthy** [GeheimagentNr1/DiscordIntegration#26]
**Versions**
Minecraft Version: [1.19.2]
Minecraft Forge Version: [43.2.14]
Mod Version: [2.2.1]

**Describe the bug**
Messages from discord server to minecraft server are not showing, only people user names are. Any idea why?

![image](https://github.com/GeheimagentNr1/DiscordIntegration/assets/73344257/974d5fb6-8665-47c0-83ba-277fb6c4dff0)

┆Issue is synchronized with this [Trello card](https://trello.com/c/t82fwytB) by [Unito](https://www.unito.io)

**Comment by GeheimagentNr1** [comment]
<table><tbody><tr><th>Status:</th><td>Further information requested</td></tr><tr><th>Issue type:</th><td>None</td></tr><tr><th>Fix type:</th><td>None</td></tr><tr><th>Fix version:</th><td>None</td></tr><tr><th>Fix release date:</th><td>None</td></tr></tbody></table>

**Issue confirmed for:**

*   None

**TODOs:**

*   [x] Test with Minecraft 1.19.2, Forge 43.2.14 and Mod version 2.2.1

**Comment by GeheimagentNr1** [comment]
I could not reproduce the issue.  
What mods/modpack are you using?  
If you use a public modpack, please provide its name.  
If you use a private modpack, please provide a list of mods or screenshots of the mods folder, so that I can build a modpack with the same mods for test purposes.
