### ISSUE TITLE
Version 1.20.1 Broken - Crash on Completed Boot

### ISSUE THREAD

**Issue by naut1cal** [GeheimagentNr1/DiscordIntegration#28]
**Versions**
Minecraft Version: 1.20.1
Minecraft Forge Version: 47.1.0
Mod Version: 1.20.1

**Log files**
https://mclo.gs/zRLgqcH

**Describe the bug**
Immediately after startup, the server crashes.

**To Reproduce**
Steps to reproduce the behaviour:
To reproduce, use the versions of Minecraft and Forge as listed, put the latest version of the Discord Integration mod into the mods folder and boot the server. Immediately after the server completes its startup, the server crashes.

**Expected behaviour**
To avoid any crashes/issues

**Screenshots**
N/A

**Additional context**
Please ask if you need any more information.

**Comment by GeheimagentNr1** [comment]
<table><tbody><tr><th>Status:</th><td>Fixed</td></tr><tr><th>Issue type:</th><td>Critical Bug</td></tr><tr><th>Fix type:</th><td>Bugfix</td></tr><tr><th>Fix version:</th><td>2.2.2</td></tr><tr><th>Fix release date:</th><td>16.07.23</td></tr></tbody></table>

**Issue confirmed for:**

*   None

**TODOs:**

*   [x] Fix for Minecraft version 1.20 and 1.20.1

**Comment by GeheimagentNr1** [comment]
@naut1cal The issue should be fixed with the new version 2.2.2.
