### ISSUE TITLE
Discord -> Minecraft chat content will be blank [1.20.1]

### ISSUE THREAD

**Issue by BobbyDevZgZ** [GeheimagentNr1/DiscordIntegration#29]
**Versions**
Minecraft Version: 1.20.1
Minecraft Forge Version: 47.1.0
Mod Version: 2.2.2

**Describe the bug**
When i text Minecraft to Discord, it works great, but when i text Discord to Minecraft no texts appears.

**To Reproduce**
Always happen to me (The server doesn't have any other mods or plugins, and it's on PloudOS hosting)
**Expected behaviour**
The Discord to Minecraft text appearing in minecraft instead of being blank.

**Screenshots**
![imagen_2023-09-13_203756379](https://github.com/GeheimagentNr1/DiscordIntegration/assets/144949312/593afb88-134e-4ca3-b1cf-3864d04a820e)

**Additional context**
Im not super fluten in English, sorry if it was bad.

**Comment by GeheimagentNr1** [comment]
Please check if the issue is fixed with version 3.0.0

**Comment by NotKevin962** [comment]
Currently running Minecraft 1.20.1 Using DI version 2.2.3 on Forge version 47.3.7 and having this problem. Is the solution to use the newer version?
