### ISSUE TITLE
Config for join/leave Minecraft messages

### ISSUE THREAD

**Issue by Nincodedo** [GeheimagentNr1/DiscordIntegration#3]
**Describe the solution you'd like**
I would like to have config options to disable the join/leave Minecraft messages that get sent to Discord.

**Comment by GeheimagentNr1** [comment]
What bothers you about the join / leave messages?

**Comment by Nincodedo** [comment]
Sometimes we are testing stuff and having join/leave messages spammed gets annoying. I only want the actual chat messages to be sent between Minecraft and Discord.

**Comment by GeheimagentNr1** [comment]
<table><tbody><tr><th>Status:</th><td>Implemented</td></tr><tr><th>Issue type:</th><td>New feature</td></tr><tr><th>Fix type:</th><td>New feature</td></tr><tr><th>Fix version:</th><td>2.1.0</td></tr><tr><th>Fix release date:</th><td>26.07.2021</td></tr></tbody></table>
