### ISSUE TITLE
presence of discordintegration causes modded biomes to be entirely shuffled in a previously existing world. i do not know why

### ISSUE THREAD

**Issue by CtrlAltSpray** [GeheimagentNr1/DiscordIntegration#30]
**Versions**
Minecraft Version: 1.16.5
Minecraft Forge Version: 36.2.0
Mod Version: 2.1.1

**Log files**
Please append the log, debug-log and if available the crash-log files

**Describe the bug**
this mod, for some reason, fucks with biomes. i dont know why. i do not know how. but. whatever man. i just got done with like 3 hours of troubleshooting only to find that the issue to my problems was "Remove This Mod" and it is so horrifically absurd i need to share it because i dont want anyone else to ever go through this

ANYWAY.

i ran a minecraft server with about 50 mods that all functionally coexisted. upon discordint's addition, every modded biome was severely misplaced, resulting in effects such as "betterend:sulphur_springs" appearing where there was previously a "byg:bayou", and many more cases. notably, this did NOT affect vanilla biomes. at all. 
given the conditions (that i wont go into, its irrelevant) it was not immediately clear that discordintegration was causing this, and instead i had believed that somehow the files had simply. corrupted? on their own??? because i didnt know what to believe. 
i figured it out when, upon changing *nothing* and simply importing the server world into my singleplayer worlds, it worked like magic-- because discordint isnt installed on the client.

it is the presence of discordintegration that causes these issues, and the removal of discordintegration immediately undid the biome swapping.

no other mod was added when discordintegration was added. this behavior was never seen prior to discordintegration being added. also, this seems to affect all 3 dimensions-- unsure about modded dimensions

**To Reproduce**
Steps to reproduce the behaviour:
1. run a modded minecraft server, note the modded biomes
2. stop server, add discordint
3. start server again. modded biomes are entirely out of wack

**Expected behaviour**
discordintegration has literally zero effect on the biomes of a minecraft world

**Screenshots**
![image](https://github.com/GeheimagentNr1/DiscordIntegration/assets/126529071/05442cf5-a414-4ab5-be50-af878c91f78e)
note that the terrain is very much of a byg bayou, and that there are clouds in the sky and i am in the overworld

**Additional context**
im fully aware that the support for this version of the mod is long dead, and that the eyes are on 1.19/1.20 now. i make this post because there is not even a single mention of the word "biome" on the issues page of this github and there's a fair shot that this issue still exists in newer versions of the mod. someone unsuspecting could be subject to this glitch and, reasonably so, would never guess in a million years that a mod for discord-minecraft chat integration has any effect on the biome-map of a minecraft world. 

(also; i am quite sure that this has no effect on a world that is generated _after_ discordintegration is added. it only means something if the mod is added into a pre-existing modpack and pre-existing world)

**Comment by CtrlAltSpray** [comment]
i should also note that there was zero trace or evidence of this occuring in the logs, so thats why there is none. i read them up and down. i assure you they are not relevant

**Comment by GeheimagentNr1** [comment]
<table><tbody><tr><th>Status:</th><td>Won't fix (cannot be reproduced)</td></tr><tr><th>Issue type:</th><td>None</td></tr><tr><th>Fix type:</th><td>None</td></tr><tr><th>Fix version:</th><td>None</td></tr><tr><th>Fix release date:</th><td>None</td></tr></tbody></table>

**Issue confirmed for:**

*   None

**TODOs:**

*   [x] Test with Minecraft 1.16.5, Minecraft Forge Version: 36.2.0, Mod Version: 2.1.1, [Oh The Biomes You'll Go 1.3.6](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go), [BetterEnd Reforked 2.5](https://www.curseforge.com/minecraft/mc-mods/betterend-re-forked)

**Comment by GeheimagentNr1** [comment]
Test steps:  
1.) Set up a Modpack with Minecraft 1.16.5, Minecraft Forge Version: 36.2.0, Oh The Biomes You'll Go 1.3.6, BetterEnd Reforked 2.5  
2.) Build a server and a client Modpack  
3.) Start the server  
4.) Port to a byg:bayou biome in the overworld (And look around)  
5.) Stop the server  
6.) Add Discord Integration 2.1.1  
7.) Start the server  
8.) Look around and check for changes.

Conclusion:  
No changes could be found. The issue cannot be reproduced and the ticket/issue will be closed.

**Comment by CtrlAltSpray** [comment]
i think its possible that it was a result of biome id swapping that was better assisted by the fact that i had many, many more mods in there that all added a buncha different biomes. so the glitch i experienced is probably extremely one in a million and not worth worrying about. apologies for the insanity of my original post but i was just so out of my mind when i wrote that after learning what the cause was
