### ISSUE TITLE
Discord Integration config reset on server shutdown

### ISSUE THREAD

**Issue by Erie-Extrones** [GeheimagentNr1/DiscordIntegration#31]
### Minecraft Version

1.19.2

### Minecraft Forge Version

43.2.14

### Mod Version

1.19.2-3.0.0

### Describe the bug

Upon the first time setting up the mod every time I would try to setup the config. while setting up the config the server was running. Once everything was set up, I went ahead and restart the server for the config to take effect. I noticed on shutdown the config would get wiped.

I went ahead and shutdown the server then edited the config, once I did that it started working normally. Just thought you should know.

### Expected behavior

The config would take affect after the restart.

### Steps to reproduce

1. Have server running
2. edit the config
3. restart server
4. config may or may not be reset to the template.

**Comment by GeheimagentNr1** [comment]
That is a known issue in many mods, but it is more an issue of forge or the toml library than of the different mods.  
  
The config is always saved on shutdown of a forge server. But if the config change is not recognized, if the server is running, the old version of the config is saved.
