### ISSUE TITLE
Spark tps custom command doesnt work in discord chat

### ISSUE THREAD

**Issue by DreiPixel** [GeheimagentNr1/DiscordIntegration#4]
**Versions**
Minecraft Version: 1.16.5
Minecraft Forge Version: 36.1.0
Mod Version: 2.0.0

**Log files**
No Log

**Describe the bug**
i tried to add a custom command. i wanted to add "Spark Tps" as a discord command but somehow when i typed it into the Discord chat the bot just said ``````. the command works fine everywhere else.

**To Reproduce**
Steps to reproduce the behaviour:
1. add spark to server
2. add command to the config with "Spark Tps"
3. try to type in a discord chat
4. ???

**Expected behaviour**
it should of course give the right output of the command which should look something like this:

[⚡] TPS from last 5s, 10s, 1m, 5m, 15m:
[⚡]  20.0, *20.0, 20.0, *20.0, *20.0
[⚡]
[⚡] Tick durations (min/med/95%ile/max ms) from last 10s, 1m:
[⚡]  0,6/1,1/1,4/1,9;  0,4/1,1/1,5/2,2
[⚡]
[⚡] CPU usage from last 10s, 1m, 15m:
[⚡]  2%, 2%, 8%  (system)
[⚡]  2%, 2%, 7%  (process)

**Comment by GeheimagentNr1** [comment]
How does the config of your command look like?

**Comment by DreiPixel** [comment]
[[commands]]
	#Minecraft command without prefix ('/')
	minecraft_command = "spark tps"
	#Dicord command without prefix
	discord_command = "spark tps"
	#Description for the help command
	description = "shows the tps statistic of the server and it's dimensions."
	#Should the command be active?
	enabled = true

**Comment by GeheimagentNr1** [comment]
Did you enter the command with the command prefix?  
I tested this with the command\_prefix "!" and the command "!spark tps" worked.

**Comment by DreiPixel** [comment]
yeah i did. the Bot just answered with a ``````. maybe im missing a step somewhere.

**Comment by DreiPixel** [comment]
i did some stuff on my server and noticed that when i try to send the command via RCON and get the response, the response is also empty. all other commands work fine. so its not your mod :/

**Comment by GeheimagentNr1** [comment]
Yes, I have looked at the source of spark tps and saw, that the implementation is not like the normal command implementation of Forge.  
So this bug, will not be fixed.
