### ISSUE TITLE
Summoned Wolf was squished too much

### ISSUE THREAD

**Issue by TheTechPny** [GeheimagentNr1/DiscordIntegration#6]
**Is your feature request related to a problem? Please describe.**
The problem is that the bot relays deaths of tamed animals. This is a problem because some mods allow you to spawn tamed animals + other mods require you to kill tamed animals. What ends up happening is the discord is spammed with "X killed Summoned Wolf"

**Describe the solution you'd like**
A simple true/false for tamed animals

**Describe alternatives you've considered**
The only alternative is to remove the check for tamed animals manually

**Additional context**
https://imgur.com/a/AWj1r8Z

**Comment by GeheimagentNr1** [comment]
<table><tbody><tr><th>Status:</th><td>Implemented</td></tr><tr><th>Issue type:</th><td>New feature</td></tr><tr><th>Fix type:</th><td>New feature</td></tr><tr><th>Fix version:</th><td>2.1.0</td></tr><tr><th>Fix release date:</th><td>26.07.2021</td></tr></tbody></table>
