### ISSUE TITLE
Censor

### ISSUE THREAD

**Issue by TheTechPny** [GeheimagentNr1/DiscordIntegration#7]
**Is your feature request related to a problem? Please describe.**
When people get toxic in the server and you don't want that getting into the discord to violate TOS or anything

**Describe the solution you'd like**
A simple censor that compares the words exactly, doesn't have to be wildcard. The censor would simply not relay the message back and forth if it's triggered

**Comment by GeheimagentNr1** [comment]
Wouldn't it be an easy solution to set up chat rules, that players must adhere to, to ensure Discord's TOS are adhered to?
And if the users do not adhere to them, they will first receive a warning and if they continue to violate the rules, they will be temporarily banned.

**Comment by TheTechPny** [comment]
> Wouldn't it be an easy solution to set up chat rules, that players must adhere to, to ensure Discord's TOS are adhered to?
> And if the users do not adhere to them, they will first receive a warning and if they continue to violate the rules, they will be temporarily banned.

For a properly staffed server sure. However due to the nature of my server it's just me as the only staff member and I don't have time to babysit the playerbase. I would just implement a censor mod but it would still go into the Discord Integration chat.

Just a simple check would be enough for me to go in and make a detailed list of naughty words/phrases

**Comment by GeheimagentNr1** [comment]
Do you have implemented a censor mod?  
If yes, how does it work? Does it simple cancels the  ServerChatEvent?  
If yes, I could simply implement, that messages of canceled ServerChatEvent will not be sent to the Disord chat.

**Comment by TheTechPny** [comment]
I have added a vanish mod before and it would hide the join/leave server message from the chat however the Discord would still show it. I just assumed that any censor mods would have the same effect

**Comment by GeheimagentNr1** [comment]
Do you have a mod, that would censor the chat messages?  
Then I could try to look at the source code and implement, that the censoring of the mod is used.

**Comment by TheTechPny** [comment]
Yes, my censor mod will cancel ServerChatEvent for compatability.

**Comment by GeheimagentNr1** [comment]
OK. I will add for the ServerChatEvent, that no message will be sent to Discord, if the ServerChatEvent is canceled.  
For your information: All other messages (server started, player joined, etc.), can be disabled in the config with version 2.1.0

**Comment by TheTechPny** [comment]
Awesome thanks!

**Comment by GeheimagentNr1** [comment]
<table><tbody><tr><th>Status:</th><td>Implemented</td></tr><tr><th>Issue type:</th><td>New Feature</td></tr><tr><th>Fix type:</th><td>New feature</td></tr><tr><th>Fix version:</th><td>2.2.0</td></tr><tr><th>Fix release date:</th><td>05.08.2021</td></tr></tbody></table>

**TODOs:**

*   [x] Implementing, that messages of cancelled ServerChatEvents will not be sent to the Discord chat.

**Comment by TheTechPny** [comment]
Are you discontinuing support for 1.16?

**Comment by GeheimagentNr1** [comment]
## Support

| Support | Supported Minecraft Versions |
| --- | --- |
| New Development and Fixes | 1.17.1 |
| Bug Fixes | 1.16.5 |
| Critical Bug Fixes | 1.15.2 |
| End of Support | 1.14.4, 1.16.1-1.16.4 |

[https://github.com/GeheimagentNr1/DiscordIntegration/wiki](https://github.com/GeheimagentNr1/DiscordIntegration/wiki)

**Comment by TheTechPny** [comment]
Thank you for the awesome work on this, your time is appreciated.

**Comment by TheTechPny** [comment]
Could you please push this to 1.16? I'd consider this a bug fix since current censor mods don't work with this version. I really would like to have this on my modded server and I can't just update to 1.17

**Comment by GeheimagentNr1** [comment]
I try to do this in the next days.

**Comment by GeheimagentNr1** [comment]
<table><tbody><tr><th>Status:</th><td>Implemented</td></tr><tr><th>Issue type:</th><td>New Feature</td></tr><tr><th>Fix type:</th><td>Bug fix</td></tr><tr><th>Fix version:</th><td>2.1.1</td></tr><tr><th>Fix release date:</th><td>10.08.2021</td></tr></tbody></table>

**TODOs:**

*   [x] Implementing, that messages of cancelled ServerChatEvents will not be sent to the Discord chat.

**Comment by TheTechPny** [comment]
You are awesome!
