### ISSUE TITLE
Spark Healthreport

### ISSUE THREAD

**Issue by TheTechPny** [GeheimagentNr1/DiscordIntegration#8]
**Is your feature request related to a problem? Please describe.**
Spark Healthreport doesn't display properly in the chat

**Describe the solution you'd like**
l would like for players to be able to view a healthreport for the server

**Describe alternatives you've considered**
A custom health report command but that seems like too much effort

**Additional context**
https://imgur.com/a/Kizb8nr - What it looks like in the Discord
https://imgur.com/a/KqRGro8 - What it looks like in-game

**Comment by GeheimagentNr1** [comment]
The Spark mod does not use the normal command implementation of Forge.  
The problem won't be fixed.  
(See #4)
