### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by Freddo3000** [GeheimagentNr1/DiscordIntegration#9]
**Is your feature request related to a problem? Please describe.**
It is a bit annoying to manage a whitelist manually.

**Describe the solution you'd like**
The bot should be able to link a minecraft account to a discord account, and check whether they have a certain role(s) in order to be able to join the minecraft server.

**Describe alternatives you've considered**
n/a

**Additional context**
https://www.curseforge.com/minecraft/mc-mods/dcintegration has this functionality, but it is currently seemingly broken.

┆Issue is synchronized with this [Trello card](https://trello.com/c/NqRAXw8g) by [Unito](https://www.unito.io)

**Comment by Coolkc456** [comment]
Agreed and I definitely need this. :) Can confirm that dcintegration is broken.

**Comment by GeheimagentNr1** [comment]
<table><tbody><tr><th>Status:</th><td>Released</td></tr><tr><th>Issue type:</th><td>New Feature</td></tr><tr><th>Fix type:</th><td>New feature</td></tr><tr><th>Fix version:</th><td>3.0.0</td></tr><tr><th>Fix release date:</th><td>12.11.2023</td></tr></tbody></table>

**TODOs:**

*   [x] Add a secure whitelist, that can be managed from Discord.

**Comment by GeheimagentNr1** [comment]
More details about the whitelist feature can be found in the [Wiki](https://github.com/GeheimagentNr1/DiscordIntegration/wiki/3.X.X#whitelist).

Implemented with version 3.0.0 for Minecraft 1.18.1, 1.18.2, 1.19.2, 1.19.4 and 1.20.2
CurseForge: https://www.curseforge.com/minecraft/mc-mods/discord-integration
Modrith: https://modrinth.com/mod/discord-integration-(di)

**Comment by Freddo3000** [comment]
Well that was a bit of a blast from the past. Glad to see it implemented.
